import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// avoid-hardcoded-colors (spec 01 §1.6 / §1.7) — test-based enforcement (防线1 fallback while the
/// custom_lint plugin is deferred on the beta toolchain; see analysis_options.yaml note). Business
/// code under lib/ must source colors from StuchkaSemanticColors / StuchkaTokens, never a raw
/// `Color(0x..)` literal or a Material `Colors.*` palette reference.
///
/// Sanctioned writers of Color literals (the token plumbing) are excluded:
///   - lib/theme/generated/tokens.g.dart   (generated by tools/gen_tokens.dart)
///   - lib/theme/stuchka_theme.dart        (assembles ThemeData from the generated tokens)
///
/// The custom_lint rule in tools/lints/lib/src/avoid_hardcoded_colors.dart encodes the same policy
/// at editor-time; this scan is the deterministic CI gate today.
void main() {
  test('lib/ business code has no hardcoded Color(0x..) / Colors.* literals', () async {
    final offenders = <String>[];
    // `Color(0x..)`, `Color.fromARGB(`, `Color.fromRGBO(`, and `Colors.<name>`.
    final colorCtor = RegExp(r'(?<![A-Za-z_.])Color(\.fromARGB|\.fromRGBO)?\s*\(\s*0x', caseSensitive: true);
    final colorsPalette = RegExp(r'(?<![A-Za-z_.])Colors\.[a-zA-Z]');

    const allowedSuffixes = <String>[
      'lib/theme/generated/tokens.g.dart',
      'lib/theme/stuchka_theme.dart',
    ];

    final dir = Directory('lib');
    expect(dir.existsSync(), isTrue, reason: 'lib/ must exist');

    await for (final entity in dir.list(recursive: true)) {
      if (entity is! File || !entity.path.endsWith('.dart')) continue;
      final normalized = entity.path.replaceAll('\\', '/');
      if (allowedSuffixes.any(normalized.endsWith)) continue;

      final content = await entity.readAsString();
      for (final line in content.split('\n')) {
        // Allow comments to mention colors.
        final code = line.split('//').first;
        if (colorCtor.hasMatch(code) || colorsPalette.hasMatch(code)) {
          offenders.add('${entity.path}: ${line.trim()}');
        }
      }
    }

    expect(
      offenders,
      isEmpty,
      reason: 'Use StuchkaSemanticColors / StuchkaTokens, not raw Color literals. Offenders:\n'
          '${offenders.join('\n')}',
    );
  });
}
