//! Dialect abstraction (backend/02 §2.11 / backend/05 §5.6, D2).
//!
//! L0-03 spike selected **SQLite** for R1 (see
//! `.trellis/tasks/06-02-db-layer/research/L0-03-db-spike.md`). Per backend/05
//! §5.6, `dialect.rs` does NOT ship a dual source in R1 — it materializes only the winning
//! (SQLite) dialect. The `Dialect` enum keeps the seam so R2 can reintroduce Postgres if a
//! cross-platform reassessment (§5.7.3) reopens the spike; the Postgres DDL draft is preserved
//! under `migrations/postgres/` for that path.

use std::fmt;

/// Supported SQL dialects. R1 only generates [`Dialect::Sqlite`]; [`Dialect::Postgres`] is a
/// reserved seam whose DDL lives as a draft under `migrations/postgres/` (D2 §2.11).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Dialect {
    /// R1 winning dialect (L0-03). UUID->TEXT, ENUM->TEXT+CHECK, JSONB->TEXT, NUMERIC->TEXT.
    Sqlite,
    /// Reserved for R-phase; not generated in R1 (backend/05 §5.6).
    Postgres,
}

impl Dialect {
    /// The dialect actually generated by R1 (L0-03 conclusion: SQLite).
    pub const R1: Dialect = Dialect::Sqlite;

    /// True when this dialect is the one R1 materializes.
    pub const fn is_r1_active(self) -> bool {
        matches!(self, Dialect::Sqlite)
    }

    /// Whether a `bool` is stored as an integer (SQLite) rather than a native boolean.
    pub const fn bool_as_integer(self) -> bool {
        matches!(self, Dialect::Sqlite)
    }

    /// Whether `UUID` is stored as `TEXT` (SQLite fallback, data/01 §1.0.5).
    pub const fn uuid_as_text(self) -> bool {
        matches!(self, Dialect::Sqlite)
    }

    /// Whether money (`NUMERIC`) is stored as a fixed-point `TEXT` string (SQLite; REAL forbidden).
    pub const fn money_as_text(self) -> bool {
        matches!(self, Dialect::Sqlite)
    }
}

impl fmt::Display for Dialect {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Dialect::Sqlite => f.write_str("sqlite"),
            Dialect::Postgres => f.write_str("postgres"),
        }
    }
}

impl Default for Dialect {
    fn default() -> Self {
        Dialect::R1
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn r1_is_sqlite() {
        assert_eq!(Dialect::R1, Dialect::Sqlite);
        assert!(Dialect::default().is_r1_active());
        assert!(!Dialect::Postgres.is_r1_active());
    }

    #[test]
    fn sqlite_fallback_flags() {
        let d = Dialect::Sqlite;
        assert!(d.uuid_as_text());
        assert!(d.money_as_text());
        assert!(d.bool_as_integer());
    }
}
